language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
install:
  - npm install -g firebase-tools
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: firebase
  token:
    secure: $DESIGN_TOKEN
  project: 'design-system'
  edge: true
  keep_history: true
  message: 'New deploy'
